server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://ljm:164411@1.15.244.26:27017/test


#logging:
#  file:
#    name: scl-server.log
#    path: /opt/log
#  config: classpath:logback-spring.xml

#file:
#  #远程访问连接前缀
#  remote-url: https://file.jim.jx.cn
#  #服务器实际存储文件根目录路径
#  path: /opt/file
