server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://jim:xxxxx@xxxxxxxxx:27017/jimTest
      #uri: mongodb://jim:xxxxxx@127.0.0.1:27017/jimTest

# 系统自定义配置
system:
  load:
    # 表的结构信息所在位置
    path: properties/model.properties
    # 注意先后顺序
    tables: sys_table,sys_role,sys_user,sys_token,sys_api
  user:
    # 系统默认的超级管理员
    supermanager:
      username: admin
      nickname: admin
      password: 123456
      role: supermanager

