server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://jim:164411@202.122.39.37:27017/jimTest
  redis:
    host: 127.0.0.1
    password: 164411
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

manager:
  id: ljm@ihep.ac.cn
  nickname: admin
  password: 123456
  role: manager
